<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->title; ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <h1><?php echo $this->h1; ?></h1>
        <h2><?php echo $this->h2a; ?></h2>
        <p><?php echo $this->pa; ?></p>
        <h2><?php echo $this->h2b; ?></h2>
        <p><?php echo $this->pb; ?></p>
    </body>
</html>
