<form method="post" action="base.php">
    <label for="login">Login</label>
    <input type="text" name="login" autocomplete="off" value="<?php echo $this->formData->login; ?>"/>
    <?php if ($this->formErrors->login) : ?>
        <span>This field must not be empty</span>
    <?php endif; ?>
    <br/>
    <label for="password">Password</label>
    <input type="password" name="password" autocomplete="off"/>
    <?php if ($this->formErrors->password) : ?>
        <span>This field must not be empty</span>
    <?php endif; ?>
    <br/>
    <button type="submit">OK</button>
</form>